simple ci file

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -4,7 +4,7 @@ jobs:
   # Variable expansion in working_directory not supported at this time
   # You will need to modify the code below to reflect your github account/repo setup
   working_directory: /go/src/github.com/nrmoorthy/invoicer-chapter2
-  
+
   docker:
    - image: circleci/golang:1.11.1
   environment:
@@ -26,59 +26,68 @@ jobs:
    - run: mkdir -p "${GOPATH_HEAD}/bin"
    - run: go get github.com/govend/govend
 
-   - run:
-       name: Build application container
-       command: |
-         go install --ldflags '-extldflags "-static"' github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME};
-         [ ! -e bin ] && mkdir bin;
-         cp "${GOPATH_HEAD}/bin/${CIRCLE_PROJECT_REPONAME}" bin/invoicer;
-         docker build -t ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME} .;
-
-
-   - run:
-       name: Run application in background
-       command: |
-         docker run ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME}
-       background: true
-
-   #- run: docker volume create myvol
-   - run:
-       name: ZAP baseline test of application
-       # Only fail on error code 1, which indicates at least one FAIL was found.
-       # error codes 2 & 3 indicate WARN or other, and should not break the run
-       command: |
-         (
-         docker pull owasp/zap2docker-weekly && \
-         docker run -t owasp/zap2docker-weekly zap-baseline.py \
-             -u https://raw.githubusercontent.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/mybranch/zap-baseline.conf \
-             -t http://172.17.0.2:8080/ || \
-         if [ $? -ne 1 ];
-            then
-                exit 0;
-            else
-                exit 1;
-         fi;
-         )
    # - run:
-   #     name: Test dependencies are up to date
-   #     command: 'GOPATH="${GOPATH_HEAD}"; ( cd ${GOPATH_BASE}/${CIRCLE_PROJECT_REPONAME} && govend -u --prune && git diff --quiet )'
+   #     name: Build application container
+   #     command: |
+   #       go install --ldflags '-extldflags "-static"' github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME};
+   #       [ ! -e bin ] && mkdir bin;
+   #       cp "${GOPATH_HEAD}/bin/${CIRCLE_PROJECT_REPONAME}" bin/invoicer;
+   #       docker build -t ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME} .;
 
-   - run:
-      name: Testing application
-      command: |
-          go test \
-          github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
+
+   # - run:
+   #     name: Run application in background
+   #     command: |
+   #       docker run ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME}
+   #     background: true
+
+   # #- run: docker volume create myvol
+   # - run:
+   #     name: ZAP baseline test of application
+   #     # Only fail on error code 1, which indicates at least one FAIL was found.
+   #     # error codes 2 & 3 indicate WARN or other, and should not break the run
+   #     command: |
+   #       (
+   #       docker pull owasp/zap2docker-weekly && \
+   #       docker run -t owasp/zap2docker-weekly zap-baseline.py \
+   #           -u https://raw.githubusercontent.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/mybranch/zap-baseline.conf \
+   #           -t http://172.17.0.2:8080/ || \
+   #       if [ $? -ne 1 ];
+   #          then
+   #              exit 0;
+   #          else
+   #              exit 1;
+   #       fi;
+   #       )
+   # # - run:
+   # #     name: Test dependencies are up to date
+   # #     command: 'GOPATH="${GOPATH_HEAD}"; ( cd ${GOPATH_BASE}/${CIRCLE_PROJECT_REPONAME} && govend -u --prune && git diff --quiet )'
+   #
+   # - run:
+   #    name: Testing application
+   #    command: |
+   #        go test \
+   #        github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
 
    - deploy:
        #Push application container to dockerhub
+       # command: |
+       #   if [ "${CIRCLE_BRANCH}" == "master" ]; then
+       #       docker login -u ${DOCKER_USER} -p ${DOCKER_PASS};
+       #       echo ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG};
+       #       go install --ldflags '-extldflags "-static"' github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME};
+       #       [ -d bin ] || mkdir bin;
+       #       cp "$GOPATH_HEAD/bin/${CIRCLE_PROJECT_REPONAME}" bin/invoicer;
+       #       docker build -t ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME} .;
+       #       docker images --no-trunc | awk '/^app/ {print $3}' | sudo tee $CIRCLE_ARTIFACTS/docker-image-shasum256.txt;
+       #       docker push ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME};
+       #   fi
        command: |
-         if [ "${CIRCLE_BRANCH}" == "master" ]; then
-             docker login -u ${DOCKER_USER} -p ${DOCKER_PASS};
-             echo ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG};
-             go install --ldflags '-extldflags "-static"' github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME};
-             [ -d bin ] || mkdir bin;
-             cp "$GOPATH_HEAD/bin/${CIRCLE_PROJECT_REPONAME}" bin/invoicer;
-             docker build -t ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME} .;
-             docker images --no-trunc | awk '/^app/ {print $3}' | sudo tee $CIRCLE_ARTIFACTS/docker-image-shasum256.txt;
-             docker push ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME};
-         fi
+           docker login -u ${DOCKER_USER} -p ${DOCKER_PASS};
+           echo ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG};
+           go install --ldflags '-extldflags "-static"' github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME};
+           [ -d bin ] || mkdir bin;
+           cp "$GOPATH_HEAD/bin/${CIRCLE_PROJECT_REPONAME}" bin/invoicer;
+           docker build -t ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME} .;
+           docker images --no-trunc | awk '/^app/ {print $3}' | sudo tee $CIRCLE_ARTIFACTS/docker-image-shasum256.txt;
+           docker push ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME};
